"""telegram subscribers

Revision ID: 19b0aa500b80
Revises: 708df79acdad
Create Date: 2026-09-24 14:28:11.610279

"""
from alembic import op
import sqlalchemy as sa


revision = '19b0aa500b80'
down_revision = '708df79acdad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_subscribers_chat_id'), 'telegram_subscribers', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_subscribers_chat_id'), table_name='telegram_subscribers')
    op.drop_table('telegram_subscribers')
    # ### end Alembic commands ###
