"""analytics indexes

Revision ID: 708df79acdad
Revises: abaa6961a13f
Create Date: 2026-09-24 13:30:30.188252

"""
from alembic import op
import sqlalchemy as sa


revision = '708df79acdad'
down_revision = 'abaa6961a13f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sessions_ended_at', 'sessions', ['ended_at'], unique=False)
    op.create_index('ix_sessions_status_ended_at', 'sessions', ['status', 'ended_at'], unique=False)
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_index('ix_sessions_status_ended_at', table_name='sessions')
    op.drop_index('ix_sessions_ended_at', table_name='sessions')
    # ### end Alembic commands ###
