"""telegram station subscriptions

Revision ID: 90c14aea710b
Revises: 19b0aa500b80
Create Date: 2026-09-24 14:39:47.087499

"""
from alembic import op
import sqlalchemy as sa


revision = '90c14aea710b'
down_revision = '19b0aa500b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_station_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['telegram_subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'station_id', name='uq_tg_sub_station')
    )
    op.create_index(op.f('ix_telegram_station_subscriptions_station_id'), 'telegram_station_subscriptions', ['station_id'], unique=False)
    op.create_index(op.f('ix_telegram_station_subscriptions_subscriber_id'), 'telegram_station_subscriptions', ['subscriber_id'], unique=False)
    op.add_column('telegram_subscribers', sa.Column('notify_all', sa.Boolean(), nullable=False, server_default=sa.true()))
    # existing subscribers should keep receiving everything
    op.alter_column('telegram_subscribers', 'notify_all', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_subscribers', 'notify_all')
    op.drop_index(op.f('ix_telegram_station_subscriptions_subscriber_id'), table_name='telegram_station_subscriptions')
    op.drop_index(op.f('ix_telegram_station_subscriptions_station_id'), table_name='telegram_station_subscriptions')
    op.drop_table('telegram_station_subscriptions')
    # ### end Alembic commands ###
