"""session comp seconds

Revision ID: f76be9c3856c
Revises: 90c14aea710b
Create Date: 2026-09-24 14:45:01.038102

"""
from alembic import op
import sqlalchemy as sa


revision = 'f76be9c3856c'
down_revision = '90c14aea710b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('comp_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('sessions', 'comp_seconds', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'comp_seconds')
    # ### end Alembic commands ###
